SELECT table_name 
FROM user_tables
WHERE table_name LIKE 'TICTACTOE%';

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE connect_four';
EXCEPTION WHEN OTHERS THEN NULL;
END;

DROP TABLE TicTacToe_Sessions

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Rating CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Moves CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Current_game CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Game_history CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Players CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TicTacToe_Rounds CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TicTacToe_Sessions CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;





CREATE TABLE Players (
    id_player NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    reg_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE Game_history (
    id_game NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    start_time DATE DEFAULT SYSDATE NOT NULL,
    end_time DATE,
    duration NUMBER,
    result VARCHAR2(100) NOT NULL,
    winner_id NUMBER,
    width NUMBER NOT NULL,
    height NUMBER NOT NULL,
    timer_enabled CHAR(1) DEFAULT 'N' CHECK (timer_enabled IN ('Y','N')),
    current_player_id NUMBER,
    CONSTRAINT fk_game_winner FOREIGN KEY (winner_id) REFERENCES Players(id_player) ON DELETE SET NULL,
    CONSTRAINT fk_game_current_player FOREIGN KEY (current_player_id) REFERENCES Players(id_player) ON DELETE SET NULL
);

CREATE TABLE Current_game (
    id_game NUMBER NOT NULL,
    id_player NUMBER NOT NULL,
    token VARCHAR2(10),
    CONSTRAINT pk_current_game PRIMARY KEY (id_game, id_player),
    CONSTRAINT fk_curr_game FOREIGN KEY (id_game) REFERENCES Game_history(id_game) ON DELETE CASCADE,
    CONSTRAINT fk_curr_player FOREIGN KEY (id_player) REFERENCES Players(id_player) ON DELETE CASCADE
);

CREATE TABLE Moves (
    id_move NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_game NUMBER NOT NULL,
    id_player NUMBER NOT NULL,
    move_time NUMBER,
    move_number NUMBER NOT NULL,
    row_pos NUMBER, 
    col_pos NUMBER,
    skip_flag CHAR(1) DEFAULT 'N' CHECK (skip_flag IN ('Y','N')),
    CONSTRAINT fk_move_game FOREIGN KEY (id_game) REFERENCES Game_history(id_game) ON DELETE CASCADE,
    CONSTRAINT fk_move_player FOREIGN KEY (id_player) REFERENCES Players(id_player) ON DELETE CASCADE
);

CREATE TABLE Rating (
    id_player NUMBER PRIMARY KEY,
    wins NUMBER DEFAULT 0,
    losses NUMBER DEFAULT 0,
    draws NUMBER DEFAULT 0,
    success NUMBER DEFAULT 0,
    CONSTRAINT fk_rating_player FOREIGN KEY (id_player) REFERENCES Players(id_player) ON DELETE CASCADE
);

CREATE TABLE TicTacToe_Sessions (
    id_session  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_game     NUMBER NOT NULL,
    id_player   NUMBER NOT NULL,
    symbol      CHAR(1) CHECK (symbol IN ('X','O')),
    CONSTRAINT fk_tttsess_game   FOREIGN KEY (id_game)  REFERENCES Game_history(id_game) ON DELETE CASCADE,
    CONSTRAINT fk_tttsess_player FOREIGN KEY (id_player) REFERENCES Players(id_player)  ON DELETE CASCADE,
    CONSTRAINT unq_tttsess UNIQUE (id_game, id_player)
);

CREATE TABLE TicTacToe_Rounds (
    id_round    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_game     NUMBER NOT NULL,
    move_number NUMBER NOT NULL,
    id_player   NUMBER NOT NULL,
    row_pos     NUMBER NOT NULL CHECK (row_pos BETWEEN 1 AND 3),
    col_pos     NUMBER NOT NULL CHECK (col_pos BETWEEN 1 AND 3),
    symbol      CHAR(1) NOT NULL CHECK (symbol IN ('X','O')),
    CONSTRAINT fk_tttr_game   FOREIGN KEY (id_game)   REFERENCES Game_history(id_game) ON DELETE CASCADE,
    CONSTRAINT fk_tttr_player FOREIGN KEY (id_player) REFERENCES Players(id_player)   ON DELETE CASCADE
);




CREATE OR REPLACE PACKAGE connect_four AS
    PROCEDURE create_player(p_name VARCHAR2);
    PROCEDURE login_player(p_name VARCHAR2);
    PROCEDURE info;
    PROCEDURE start_game(p_player1 VARCHAR2, p_player2 VARCHAR2, p_width NUMBER, p_height NUMBER, p_timer BOOLEAN);
    PROCEDURE make_move(p_game_id NUMBER, p_player_id NUMBER, p_column NUMBER);
    PROCEDURE skip_move(p_game_id NUMBER, p_player_id NUMBER);
    FUNCTION  check_winner(p_game_id NUMBER, p_last_move_id NUMBER) RETURN VARCHAR2;
    PROCEDURE update_rating(p_game_id NUMBER);
    PROCEDURE rematch(p_game_id NUMBER);
    PROCEDURE show_history(p_player VARCHAR2 := NULL, p_date_from DATE := NULL, p_date_to DATE := NULL);
    PROCEDURE show_leaderboard;
    PROCEDURE close_idle_games;
    
    PROCEDURE tic_tac_toe_resolve(p_game_id NUMBER);
    PROCEDURE make_ttt_move(
        p_game_id NUMBER, p_player_id NUMBER,
        p_row NUMBER, p_col NUMBER,
        p_symbol CHAR
    );
    FUNCTION ttt_check_winner(p_game_id NUMBER) RETURN NUMBER;

END connect_four;
/


CREATE OR REPLACE PACKAGE BODY connect_four AS
    -- проверка на активную игру
    FUNCTION player_has_active_game_by_name(p_name VARCHAR2) RETURN NUMBER IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_cnt
        FROM Current_game cg
        JOIN Players p ON p.id_player = cg.id_player
        JOIN Game_history gh ON gh.id_game = cg.id_game
        WHERE LOWER(p.name) = LOWER(p_name)
          AND gh.result = 'В процессе';
        RETURN v_cnt;
    EXCEPTION WHEN OTHERS THEN
        RETURN 0;
    END;

    -- создание игрока
    PROCEDURE create_player(p_name VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM Players WHERE LOWER(name)=LOWER(p_name);
        IF v_exists > 0 THEN
            DBMS_OUTPUT.PUT_LINE('Игрок "'||p_name||'" уже зарегистрирован.');
            RETURN;
        END IF;
        INSERT INTO Players(name, reg_date) VALUES (p_name, SYSDATE);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Игрок "'||p_name||'" зарегистрирован.');
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
    END create_player;

    -- вход
    PROCEDURE login_player(p_name VARCHAR2) IS
        v_id NUMBER;
    BEGIN
        SELECT id_player INTO v_id FROM Players WHERE LOWER(name)=LOWER(p_name);
        DBMS_OUTPUT.PUT_LINE('LOGIN_OK ID='||v_id);
    EXCEPTION WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Игрок "'||p_name||'" не найден.');
    END login_player;

    -- инфо
    PROCEDURE info IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('? ПРАВИЛА ИГРЫ ?ЧЕТЫРЕ В РЯД? ?');
        DBMS_OUTPUT.PUT_LINE('1. Цель — собрать 4 фишки подряд (по горизонтали, вертикали или диагонали).');
        DBMS_OUTPUT.PUT_LINE('2. Игроки ходят по очереди.');
        DBMS_OUTPUT.PUT_LINE('3. Фишка падает вниз выбранного столбца.');
        DBMS_OUTPUT.PUT_LINE('4. Если столбец заполнен — ход невозможен.');
        DBMS_OUTPUT.PUT_LINE('5. При включённом таймере игрок должен сделать ход за 60 секунд.');
    END info;

    -- создание игры
    PROCEDURE start_game(p_player1 VARCHAR2, p_player2 VARCHAR2, p_width   NUMBER, p_height  NUMBER, p_timer   BOOLEAN) IS
        v_id1 NUMBER; v_id2 NUMBER; v_game_id NUMBER; v_starter NUMBER; v_timer_ch CHAR(1);
    BEGIN
        IF p_width NOT BETWEEN 7 AND 10 THEN raise_application_error(-20001, 'Ширина поля должна быть 7..10.');
        END IF;
        IF p_height NOT BETWEEN 6 AND 8 THEN raise_application_error(-20002, 'Высота поля должна быть 6..8.');
        END IF;
        BEGIN
            SELECT id_player INTO v_id1 FROM Players WHERE LOWER(name)=LOWER(p_player1);
        EXCEPTION WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Игрок '||p_player1||' не найден.');
            RETURN;
        END;
        BEGIN
            SELECT id_player INTO v_id2 FROM Players WHERE LOWER(name)=LOWER(p_player2);
        EXCEPTION WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Игрок '||p_player2||' не найден.');
            RETURN;
        END;
        IF v_id1 = v_id2 THEN
            DBMS_OUTPUT.PUT_LINE('Игрок не может играть сам с собой.');
            RETURN;
        END IF;
        IF player_has_active_game_by_name(p_player1) > 0 THEN raise_application_error(-20003, 'У игрока '||p_player1||' уже есть активная игра.');
        END IF;
        IF player_has_active_game_by_name(p_player2) > 0 THEN raise_application_error(-20004, 'У игрока '||p_player2||' уже есть активная игра.');
        END IF;
        v_timer_ch := CASE WHEN p_timer THEN 'Y' ELSE 'N' END;
        INSERT INTO Game_history(start_time, width, height, result, timer_enabled) VALUES (SYSDATE, p_width, p_height, 'В процессе', v_timer_ch)
        RETURNING id_game INTO v_game_id;
        SELECT CASE WHEN DBMS_RANDOM.VALUE(0,1)<0.5 THEN v_id1 ELSE v_id2 END INTO v_starter FROM dual;
        IF v_starter = v_id1 THEN
            INSERT INTO Current_game(id_game, id_player, token) VALUES (v_game_id, v_id1, 'RED');
            INSERT INTO Current_game(id_game, id_player, token) VALUES (v_game_id, v_id2, 'YELLOW');
        ELSE
            INSERT INTO Current_game(id_game, id_player, token) VALUES (v_game_id, v_id2, 'RED');
            INSERT INTO Current_game(id_game, id_player, token) VALUES (v_game_id, v_id1, 'YELLOW');
        END IF;
        UPDATE Game_history SET current_player_id = v_starter WHERE id_game = v_game_id;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('NEW_GAME_ID='||v_game_id);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END start_game;

    -- ходы
    PROCEDURE make_move(p_game_id NUMBER, p_player_id NUMBER, p_column NUMBER) IS
        v_game_exists NUMBER; v_res VARCHAR2(200); v_curr NUMBER; v_width NUMBER; v_height NUMBER; v_col_count NUMBER;
        v_row NUMBER; v_move_num NUMBER; v_id_move NUMBER; v_opponent NUMBER; v_player_name VARCHAR2(100);
    BEGIN
        SELECT COUNT(*) INTO v_game_exists FROM Game_history WHERE id_game=p_game_id;
        IF v_game_exists=0 THEN
            DBMS_OUTPUT.PUT_LINE('Партия не найдена');
            RETURN;
        END IF;
        SELECT result, current_player_id, width, height INTO v_res, v_curr, v_width, v_height FROM Game_history WHERE id_game=p_game_id;
        IF v_res <> 'В процессе' THEN
            DBMS_OUTPUT.PUT_LINE('Партия уже завершена: '||v_res);
            RETURN;
        END IF;
        SELECT COUNT(*) INTO v_game_exists FROM Current_game WHERE id_game=p_game_id AND id_player=p_player_id;
        IF v_game_exists=0 THEN
            DBMS_OUTPUT.PUT_LINE('Игрок не участвует в партии');
            RETURN;
        END IF;
        IF v_curr <> p_player_id THEN
            DBMS_OUTPUT.PUT_LINE('Сейчас ход другого игрока');
            RETURN;
        END IF;
        IF p_column NOT BETWEEN 1 AND v_width THEN
            DBMS_OUTPUT.PUT_LINE('Неверный столбец');
            RETURN;
        END IF;
        SELECT COUNT(*) INTO v_col_count FROM Moves
        WHERE id_game=p_game_id
          AND col_pos=p_column
          AND skip_flag='N';
        IF v_col_count >= v_height THEN
            DBMS_OUTPUT.PUT_LINE('Столбец заполнен');
            RETURN;
        END IF;
        v_row := v_height - v_col_count;
        SELECT NVL(MAX(move_number),0)+1 INTO v_move_num FROM Moves WHERE id_game=p_game_id;
        INSERT INTO Moves(id_game,id_player,move_time,move_number,row_pos,col_pos,skip_flag)
        VALUES (p_game_id,p_player_id,1,v_move_num,v_row,p_column,'N')
        RETURNING id_move INTO v_id_move;

        -- смена игрока
        SELECT id_player INTO v_opponent FROM Current_game
        WHERE id_game=p_game_id AND id_player<>p_player_id
        AND ROWNUM=1;
        UPDATE Game_history SET current_player_id=v_opponent
        WHERE id_game=p_game_id;
        COMMIT;
        v_res := check_winner(p_game_id, v_id_move);
        IF v_res IS NOT NULL THEN 
            DBMS_OUTPUT.PUT_LINE('Игра завершена: '||v_res);
        END IF;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END make_move;

    -- пропуск хода
    PROCEDURE skip_move(p_game_id NUMBER, p_player_id NUMBER) IS
        v_move_num NUMBER; v_id_move NUMBER; v_opponent NUMBER; v_skip NUMBER; v_name VARCHAR2(100);
    BEGIN
        SELECT NVL(MAX(move_number),0)+1 INTO v_move_num FROM Moves WHERE id_game=p_game_id;
        INSERT INTO Moves(id_game,id_player,move_time,move_number,skip_flag) VALUES (p_game_id,p_player_id,60,v_move_num,'Y')
        RETURNING id_move INTO v_id_move;
        SELECT id_player INTO v_opponent FROM Current_game WHERE id_game=p_game_id AND id_player<>p_player_id;
        UPDATE Game_history SET current_player_id=v_opponent WHERE id_game=p_game_id;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Ход пропущен игроком '||p_player_id);
        SELECT COUNT(*) INTO v_skip
        FROM Moves WHERE id_game=p_game_id
                     AND id_player=p_player_id AND skip_flag='Y';
        IF v_skip>=3 THEN
            SELECT name INTO v_name FROM Players WHERE id_player=v_opponent;
            UPDATE Game_history
            SET end_time = SYSDATE,
                duration = ROUND((SYSDATE-start_time)*24*3600),
                winner_id = v_opponent,
                result = 'Техническое поражение — победа игрока '||v_name||' (id '||v_opponent||')'
            WHERE id_game=p_game_id;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('Техническое поражение игрока '||p_player_id);
            DBMS_OUTPUT.PUT_LINE('Победитель: '||v_name||' (id '||v_opponent||')');
            update_rating(p_game_id);
        END IF;
    END skip_move;

    -- проверка победителя
    FUNCTION check_winner(p_game_id NUMBER, p_last_move_id NUMBER)
    RETURN VARCHAR2 IS
        TYPE t_field IS TABLE OF NUMBER INDEX BY VARCHAR2(30);
        v_field t_field; v_width  NUMBER; v_height NUMBER; v_player NUMBER;
        v_r NUMBER; v_c NUMBER; v_result VARCHAR2(500);
        TYPE t_list IS TABLE OF VARCHAR2(20);
        v_win_cells t_list := t_list();
        v_player_name VARCHAR2(100);
    BEGIN
        SELECT width, height
        INTO v_width, v_height
        FROM Game_history
        WHERE id_game = p_game_id;
        FOR rec IN (
            SELECT id_player, row_pos, col_pos
            FROM Moves
            WHERE id_game = p_game_id
              AND skip_flag = 'N'
              AND row_pos IS NOT NULL
        ) LOOP
            v_field(rec.row_pos || '_' || rec.col_pos) := rec.id_player;
        END LOOP;
        SELECT id_player, row_pos, col_pos
        INTO v_player, v_r, v_c
        FROM Moves
        WHERE id_move = p_last_move_id;
        DECLARE
            TYPE t_temp_list IS TABLE OF VARCHAR2(20);
            temp_cells t_temp_list;
            PROCEDURE check_dir(dr1 NUMBER, dc1 NUMBER, dr2 NUMBER, dc2 NUMBER) IS
                cnt NUMBER := 1;
                r NUMBER;
                c NUMBER;
            BEGIN
                temp_cells := t_temp_list();
                temp_cells.EXTEND;
                temp_cells(temp_cells.LAST) := v_r || ',' || v_c;
                r := v_r + dr1;
                c := v_c + dc1;
                WHILE v_field.EXISTS(r||'_'||c)
                  AND v_field(r||'_'||c)=v_player LOOP
                    cnt := cnt + 1;
                    temp_cells.EXTEND;
                    temp_cells(temp_cells.LAST) := r||','||c;
                    r := r + dr1;
                    c := c + dc1;
                END LOOP;
                r := v_r + dr2;
                c := v_c + dc2;
                WHILE v_field.EXISTS(r||'_'||c)
                  AND v_field(r||'_'||c)=v_player LOOP
                    cnt := cnt + 1;
                    temp_cells.EXTEND;
                    temp_cells(temp_cells.LAST) := r||','||c;
                    r := r + dr2;
                    c := c + dc2;
                END LOOP;
                IF cnt >= 4 AND v_win_cells.COUNT = 0 THEN
                    FOR i IN 1..4 LOOP
                        v_win_cells.EXTEND;
                        v_win_cells(v_win_cells.LAST) := temp_cells(i);
                    END LOOP;
                END IF;
            END check_dir;
    
        BEGIN
            check_dir(0,-1, 0,1);
            check_dir(-1,0, 1,0);
            check_dir(-1,1, 1,-1);
            check_dir(-1,-1, 1,1);
        END;
        IF v_win_cells.COUNT = 4 THEN
            SELECT name INTO v_player_name
            FROM Players
            WHERE id_player = v_player;
            v_result :=
                'Победа игрока ' || v_player_name || ' (id ' || v_player || ')';
            UPDATE Game_history
            SET end_time = SYSDATE,
                duration = ROUND((SYSDATE - start_time) * 24 * 3600),
                result = v_result,
                winner_id = v_player
            WHERE id_game = p_game_id;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_result);
            DBMS_OUTPUT.PUT_LINE(
                'WIN_CELLS=' ||
                v_win_cells(1) || ';' ||
                v_win_cells(2) || ';' ||
                v_win_cells(3) || ';' ||
                v_win_cells(4)
            );
            update_rating(p_game_id);
            RETURN v_result;
        END IF;
        DECLARE
            v_cnt NUMBER;
        BEGIN
            SELECT COUNT(*) INTO v_cnt
            FROM Moves
            WHERE id_game = p_game_id
              AND skip_flag = 'N'
              AND row_pos IS NOT NULL;
            IF v_cnt >= v_width * v_height THEN
                UPDATE Game_history
                SET result = 'Ничья — крестики-нолики'
                WHERE id_game = p_game_id;
                COMMIT;
                RETURN 'Ничья — крестики-нолики';
            END IF;
        END;
        RETURN NULL;
    END check_winner;

    -- обновление рейтинга
    PROCEDURE update_rating(p_game_id NUMBER) IS
        v_res VARCHAR2(200);
        v_win NUMBER;
    BEGIN
        SELECT result, winner_id INTO v_res, v_win
        FROM Game_history WHERE id_game = p_game_id;
        INSERT INTO Rating(id_player,wins,losses,draws,success)
        SELECT id_player,0,0,0,0
        FROM Current_game cg
        WHERE cg.id_game = p_game_id
          AND NOT EXISTS (SELECT 1 FROM Rating r WHERE r.id_player=cg.id_player);
        IF v_win IS NOT NULL THEN
            UPDATE Rating SET wins=wins+1 WHERE id_player=v_win;
            UPDATE Rating SET losses=losses+1
            WHERE id_player IN (SELECT id_player FROM Current_game WHERE id_game=p_game_id AND id_player<>v_win);
        ELSE
            UPDATE Rating SET draws=draws+1
            WHERE id_player IN (SELECT id_player FROM Current_game WHERE id_game=p_game_id);
        END IF;
        UPDATE Rating
        SET success = CASE WHEN losses=0 THEN wins ELSE ROUND(wins/losses,2) END;
        COMMIT;
    END update_rating;

    -- реванш
    PROCEDURE rematch(p_game_id NUMBER) IS
        v_new_game NUMBER; v_w NUMBER; v_h NUMBER; v_t CHAR(1);
        v_p1 NUMBER; v_p2 NUMBER; v_starter NUMBER;
    BEGIN
        SELECT width, height, timer_enabled INTO v_w, v_h, v_t FROM Game_history WHERE id_game = p_game_id;
        SELECT MIN(id_player), MAX(id_player) INTO v_p1, v_p2 FROM Current_game WHERE id_game = p_game_id;
        IF v_p1 IS NULL OR v_p2 IS NULL THEN
            DBMS_OUTPUT.PUT_LINE('Невозможно реванш: недостаточно игроков');
            RETURN;
        END IF;

        INSERT INTO Game_history(start_time, width, height, result, timer_enabled)
        VALUES (SYSDATE, v_w, v_h, 'В процессе', v_t)
        RETURNING id_game INTO v_new_game;

        SELECT CASE WHEN DBMS_RANDOM.VALUE(0,1) < 0.5 THEN v_p1 ELSE v_p2 END INTO v_starter FROM dual;

        IF v_starter = v_p1 THEN
            INSERT INTO Current_game(id_game, id_player, token) VALUES (v_new_game, v_p1, 'RED');
            INSERT INTO Current_game(id_game, id_player, token) VALUES (v_new_game, v_p2, 'YELLOW');
        ELSE
            INSERT INTO Current_game(id_game, id_player, token) VALUES (v_new_game, v_p2, 'RED');
            INSERT INTO Current_game(id_game, id_player, token) VALUES (v_new_game, v_p1, 'YELLOW');
        END IF;

        UPDATE Game_history SET current_player_id = v_starter WHERE id_game = v_new_game;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('NEW_GAME_ID='||v_new_game);
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
    END rematch;

    -- история
    PROCEDURE show_history(p_player VARCHAR2 := NULL, p_date_from DATE := NULL, p_date_to   DATE := NULL) IS
        v_id NUMBER;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('ИСТОРИЯ ПАРТИЙ');
        IF p_player IS NOT NULL THEN
            BEGIN
                SELECT id_player INTO v_id
                FROM Players WHERE LOWER(name)=LOWER(p_player);
            EXCEPTION WHEN NO_DATA_FOUND THEN
                BEGIN
                    v_id := TO_NUMBER(p_player);
                EXCEPTION WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('Игрок не найден: '||p_player);
                    RETURN;
                END;
            END;
            FOR r IN (
                SELECT gh.id_game,
                       TO_CHAR(gh.start_time,'YYYY-MM-DD HH24:MI:SS') AS st,
                       TO_CHAR(gh.end_time,'YYYY-MM-DD HH24:MI:SS') AS en,
                       gh.duration,
                       CASE 
                           WHEN gh.winner_id IS NOT NULL THEN 
                               (SELECT name||' (id '||id_player||')' FROM Players WHERE id_player=gh.winner_id)
                           ELSE '-'
                       END AS winner,
                       gh.result
                FROM Game_history gh
                JOIN Current_game cg ON cg.id_game = gh.id_game
                WHERE cg.id_player = v_id
                ORDER BY gh.start_time DESC
            ) LOOP
                DBMS_OUTPUT.PUT_LINE(
                    'ID='||r.id_game||
                    ' | '||r.st||' - '||NVL(r.en,'N/A')||
                    ' | dur='||NVL(r.duration,0)||'s'||
                    ' | '||r.result||
                    ' | Победитель: '||r.winner
                );
            END LOOP;
        ELSE
            DBMS_OUTPUT.PUT_LINE('Укажите игрока: show_history(''Ivan'')');
        END IF;
    END show_history;

    -- доска лидеров
    PROCEDURE show_leaderboard IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Name | Wins | Losses | Draws | Success | Total');
        FOR r IN (
            SELECT p.name, wins, losses, draws, success,
                   (wins+losses+draws) total
            FROM Rating r
            JOIN Players p ON p.id_player=r.id_player
            WHERE (wins+losses+draws)>=10
            ORDER BY success DESC, wins DESC
        ) LOOP
            DBMS_OUTPUT.PUT_LINE(
                r.name||' | '||r.wins||' | '||r.losses||' | '||
                r.draws||' | '||r.success||' | '||r.total
            );
        END LOOP;
    END show_leaderboard;

    -- принудительное завершение игр через 3 часа
    PROCEDURE close_idle_games IS
    BEGIN
        UPDATE Game_history
        SET result='Прервано (длительное ожидание)',
            end_time = SYSDATE,
            duration = ROUND((SYSDATE-start_time)*24*3600),
            winner_id=NULL
        WHERE result='В процессе'
          AND start_time < SYSDATE - INTERVAL '3' HOUR;
        COMMIT;
    END close_idle_games;

    -- ходы крестики-нолики
    PROCEDURE make_ttt_move(
        p_game_id   NUMBER,
        p_player_id NUMBER,
        p_row       NUMBER,
        p_col       NUMBER,
        p_symbol    CHAR
    ) IS
        v_exists NUMBER;
        v_move   NUMBER;
        v_last_symbol CHAR(1);
        v_assigned_symbol CHAR(1);
    BEGIN
        IF p_row NOT BETWEEN 1 AND 3 OR p_col NOT BETWEEN 1 AND 3 THEN
            raise_application_error(-20060, 'Неверные координаты (должны быть 1..3)');
        END IF;
        SELECT symbol INTO v_assigned_symbol
        FROM TicTacToe_Sessions
        WHERE id_game = p_game_id AND id_player = p_player_id;
        IF v_assigned_symbol IS NULL THEN
            raise_application_error(-20061, 'Игроку не назначен символ для крестиков-ноликов');
        END IF;
        IF p_symbol IS NULL OR UPPER(p_symbol) <> v_assigned_symbol THEN
            raise_application_error(-20062, 'Неверный символ для этого игрока');
        END IF;
    
        BEGIN
            SELECT symbol
            INTO v_last_symbol
            FROM (
                SELECT symbol
                FROM TicTacToe_Rounds
                WHERE id_game = p_game_id
                ORDER BY move_number DESC
            ) t
            WHERE ROWNUM = 1;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            v_last_symbol := NULL;
        END;
    
        IF v_last_symbol IS NULL THEN
            IF p_symbol <> 'X' THEN
                raise_application_error(-20051, 'Первым ходит X');
            END IF;
        ELSE
            IF v_last_symbol = 'X' AND p_symbol <> 'O' THEN
                raise_application_error(-20052, 'Сейчас ход O');
            ELSIF v_last_symbol = 'O' AND p_symbol <> 'X' THEN
                raise_application_error(-20053, 'Сейчас ход X');
            END IF;
        END IF;
        SELECT COUNT(*) INTO v_exists
        FROM TicTacToe_Rounds
        WHERE id_game = p_game_id
          AND row_pos = p_row
          AND col_pos = p_col;
        IF v_exists > 0 THEN
            raise_application_error(-20050, 'Клетка уже занята');
        END IF;
        SELECT NVL(MAX(move_number), 0) + 1 INTO v_move FROM TicTacToe_Rounds WHERE id_game = p_game_id;
        INSERT INTO TicTacToe_Rounds(id_game, move_number, id_player, row_pos, col_pos, symbol)
        VALUES (p_game_id, v_move, p_player_id, p_row, p_col, UPPER(p_symbol));
    
        COMMIT;
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
    END make_ttt_move;
   
    -- победитель в крестиках
    FUNCTION ttt_check_winner(p_game_id NUMBER) RETURN NUMBER IS
        TYPE t_matrix IS TABLE OF CHAR(1) INDEX BY VARCHAR2(2);
        board     t_matrix;
        winner_id NUMBER := NULL;
    
        FUNCTION get_cell(pos VARCHAR2) RETURN CHAR IS
        BEGIN
            IF board.EXISTS(pos) THEN
                RETURN board(pos);
            ELSE
                RETURN NULL;
            END IF;
        END;
    BEGIN
        FOR r IN (
            SELECT row_pos, col_pos, symbol
            FROM TicTacToe_Rounds
            WHERE id_game = p_game_id
        ) LOOP
            board(r.row_pos || r.col_pos) := r.symbol;
        END LOOP;
        DECLARE
            TYPE t_line  IS VARRAY(3) OF VARCHAR2(2);
            TYPE t_lines IS VARRAY(8) OF t_line;
            lines t_lines := t_lines(
                t_line('11','12','13'), 
                t_line('21','22','23'),
                t_line('31','32','33'), 
                t_line('11','21','31'),
                t_line('12','22','32'), 
                t_line('13','23','33'), 
                t_line('11','22','33'), 
                t_line('13','22','31')  
            );
        BEGIN
            FOR i IN 1..lines.COUNT LOOP
                DECLARE
                    p1 CHAR(1) := get_cell(lines(i)(1));
                    p2 CHAR(1) := get_cell(lines(i)(2));
                    p3 CHAR(1) := get_cell(lines(i)(3));
                BEGIN
                    IF p1 IS NOT NULL AND p1 = p2 AND p2 = p3 THEN
                        SELECT id_player INTO winner_id
                        FROM TicTacToe_Rounds
                        WHERE id_game = p_game_id
                          AND symbol = p1
                          AND ROWNUM = 1;
    
                        RETURN winner_id;
                    END IF;
                END;
            END LOOP;
        END;
    
        DECLARE
            total_moves NUMBER;
        BEGIN
            SELECT COUNT(*) INTO total_moves
            FROM TicTacToe_Rounds
            WHERE id_game = p_game_id;
            IF total_moves = 9 THEN
                RETURN -1;
            END IF;
        END;
        RETURN NULL; 
    END ttt_check_winner;
   
    -- игра крестики
    PROCEDURE tic_tac_toe_resolve(p_game_id NUMBER) IS
        v_p1 NUMBER;
        v_p2 NUMBER;
        v_symbol_p1 CHAR(1);
        v_symbol_p2 CHAR(1);
        v_turn NUMBER;
        v_winner NUMBER;
        v_round_count NUMBER := 0;
        v_max_rounds NUMBER := 100;
    BEGIN
        SELECT MIN(id_player), MAX(id_player)
        INTO v_p1, v_p2
        FROM Current_game
        WHERE id_game = p_game_id;
    
        IF v_p1 IS NULL OR v_p2 IS NULL THEN
            raise_application_error(-20070, 'Недостаточно игроков для крестиков-ноликов');
        END IF;
    
        <<new_round>>
        v_round_count := v_round_count + 1;
        IF v_round_count > v_max_rounds THEN
            UPDATE Game_history
            SET result = 'Ничья — крестики-нолики (превышено число раундов)',
                end_time = SYSDATE,
                duration = ROUND((SYSDATE - start_time)*24*3600),
                winner_id = NULL
            WHERE id_game = p_game_id;
            COMMIT;
            update_rating(p_game_id);
            RETURN;
        END IF;

        IF DBMS_RANDOM.VALUE(0,1) < 0.5 THEN
            v_symbol_p1 := 'X'; v_symbol_p2 := 'O';
        ELSE
            v_symbol_p1 := 'O'; v_symbol_p2 := 'X';
        END IF;
    
        BEGIN
            MERGE INTO TicTacToe_Sessions ts
            USING (SELECT p_game_id pid, v_p1 p1, v_symbol_p1 s1, v_p2 p2, v_symbol_p2 s2 FROM dual) src
            ON (ts.id_game = src.pid AND ts.id_player = src.p1)
            WHEN MATCHED THEN UPDATE SET ts.symbol = src.s1
            WHEN NOT MATCHED THEN INSERT (id_game, id_player, symbol) VALUES (src.pid, src.p1, src.s1);
    
            MERGE INTO TicTacToe_Sessions ts2
            USING (SELECT p_game_id pid, v_p2 p2, v_symbol_p2 s2 FROM dual) src2
            ON (ts2.id_game = src2.pid AND ts2.id_player = src2.p2)
            WHEN MATCHED THEN UPDATE SET ts2.symbol = src2.s2
            WHEN NOT MATCHED THEN INSERT (id_game, id_player, symbol) VALUES (src2.pid, src2.p2, src2.s2);
        EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
        END;
        COMMIT;
    
        IF v_symbol_p1 = 'X' THEN
            v_turn := v_p1;
        ELSE
            v_turn := v_p2;
        END IF;
    
        DELETE FROM TicTacToe_Rounds WHERE id_game = p_game_id;
        COMMIT;

        LOOP
            NULL;
            v_winner := ttt_check_winner(p_game_id);
    
            IF v_winner IS NOT NULL THEN
                IF v_winner = -1 THEN
                    DELETE FROM TicTacToe_Rounds WHERE id_game = p_game_id;
                    COMMIT;
                    GOTO new_round;
                ELSE
                    DECLARE v_name VARCHAR2(100);
                    BEGIN
                        SELECT name INTO v_name FROM Players WHERE id_player = v_winner;
                        UPDATE Game_history
                        SET result = 'Победа игрока '||v_name||' (крестики-нолики)',
                            winner_id = v_winner,
                            end_time = SYSDATE,
                            duration = ROUND((SYSDATE - start_time)*24*3600)
                        WHERE id_game = p_game_id;
                        COMMIT;
                    END;
                    update_rating(p_game_id);
                    RETURN;
                END IF;
            END IF;
    
            DECLARE total_moves NUMBER;
            BEGIN
                SELECT COUNT(*) INTO total_moves FROM TicTacToe_Rounds WHERE id_game = p_game_id;
                IF total_moves >= 9 THEN
                    DELETE FROM TicTacToe_Rounds WHERE id_game = p_game_id;
                    COMMIT;
                    GOTO new_round;
                END IF;
            END;
        END LOOP;
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
    END tic_tac_toe_resolve;



END connect_four;
/






SET SERVEROUTPUT ON;
EXEC connect_four.create_player('Dasha1');
EXEC connect_four.create_player('Liza1');

EXEC connect_four.login_player('DAsha1');
EXEC connect_four.info;
EXEC connect_four.login_player('Liza1');

EXEC connect_four.start_game('Dasha1', 'Liza1', 7, 6, TRUE);

EXEC connect_four.make_move(1, 10, 3);

EXEC connect_four.make_move(47, 1, 2);
EXEC connect_four.make_move(47, 2, 3);

--  пропуск
EXEC connect_four.skip_move(2, 1);
EXEC connect_four.skip_move(2, 2);

EXEC connect_four.show_history('3');

EXEC connect_four.show_leaderboard;


EXEC connect_four.rematch(1);


EXEC connect_four.close_idle_games;


BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name => 'CLOSE_IDLE_GAMES_JOB',
        job_type => 'PLSQL_BLOCK',
        job_action => 'BEGIN connect_four.close_idle_games; END;',
        start_date => SYSTIMESTAMP,
        repeat_interval => 'FREQ=HOURLY; INTERVAL=3',
        enabled => TRUE,
        comments => 'Запуск процедуры закрытия неактивных игр каждые 3 часа'
    );
END;
/

SELECT job_name, enabled, state, last_start_date, next_run_date
FROM user_scheduler_jobs
WHERE job_name = 'CLOSE_IDLE_GAMES_JOB';


BEGIN
    DBMS_SCHEDULER.ENABLE('CLOSE_IDLE_GAMES_JOB');
END;
/

BEGIN
    DBMS_SCHEDULER.DISABLE('CLOSE_IDLE_GAMES_JOB');
END;
/

BEGIN
    DBMS_SCHEDULER.DROP_JOB('CLOSE_IDLE_GAMES_JOB');
END;
/

-- Создай тестовую игру с ничьёй
INSERT INTO Game_history (game_id, player1_id, player2_id, result)
VALUES (999, 101, 102, 'Ничья');

-- Вызови процедуру разрешения
BEGIN
  connect_four.tic_tac_toe_resolve(12);
END;
/



SELECT game_id, player1_id, player2_id, result, game_type
FROM Game_history
WHERE game_id = 12;




DESC TicTacToe_Sessions;
DESC TicTacToe_Rounds;
DESC Game_history;
DESC Players;
DESC Current_game;
DESC Rating;




EXEC connect_four.create_player('P1');
EXEC connect_four.create_player('P2');
EXEC connect_four.start_game('P1', 'P2', 7, 6, FALSE);

UPDATE Game_history
SET result = 'Ничья — крестики-нолики'
WHERE id_game = :1;

-- заполнить столб 1
EXEC connect_four.make_move(1, 1, 1);
EXEC connect_four.make_move(1, 2, 1);

-- заполнить столб 2
EXEC connect_four.make_move(1, 1, 2);
EXEC connect_four.make_move(1, 2, 2);

-- заполнить столб 3
EXEC connect_four.make_move(1, 1, 3);
EXEC connect_four.make_move(1, 2, 3);

-- заполнить столб 5
EXEC connect_four.make_move(1, 1, 5);
EXEC connect_four.make_move(1, 2, 5);

-- заполнить столб 6
EXEC connect_four.make_move(1, 1, 6);
EXEC connect_four.make_move(1, 2, 6);
EXEC connect_four.make_move(1, 1, 6);
EXEC connect_four.make_move(1, 2, 6);
EXEC connect_four.make_move(1, 1, 6);

-- заполнить столб 4
EXEC connect_four.make_move(1, 1, 4);
EXEC connect_four.make_move(1, 2, 4);

-- заполнить столб 7
EXEC connect_four.make_move(1, 1, 7);
EXEC connect_four.make_move(1, 2, 7);



SET SERVEROUTPUT ON;
BEGIN
  connect_four.tic_tac_toe_resolve(1);
END;
/

SELECT * FROM Current_game WHERE id_game = 1;

SELECT * FROM game_history;

SELECT cg.id_game, cg.id_player, p.name
FROM Current_game cg
JOIN Players p ON p.id_player = cg.id_player
WHERE cg.id_game = 1;
